title: Nishanth Sivanandam's Portfolio
description: Machine Learning Scientist | Edge AI & Safety-Critical Vision Systems

# This is the theme that will be used for your site.
# You can find other supported themes here: https://pages.github.com/themes/
theme: jekyll-theme-cayman